name: Update Heatmap

on:
  schedule: 
    - cron: '0 2 * * *'    # every day at 02:00 UTC
  workflow_dispatch:       # allow manual trigger
  # push:                    # trigger on every new commit
  #   branches:
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install plotly and dependencies
        run: pip install numpy pandas requests plotly kaleido

      - name: Generate Heatmap
        run: python heatmap.py
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          RUN_LOCALLY: 'False'

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add images/running_heatmap.svg docs/running_heatmap.html
          git commit -m "Dailty Running Heatmap Update" || echo "No changes to commit"
          git push
