name: Update Heatmap

on:
  schedule: 
    - cron: '0 2 * * *'    # every day at 02:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install plotly and dependencies
        run: pip install numpy pandas datetime collections requests plotly kaleido

      - name: Generate heatmap
        run: python heatmap.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add images/running_heatmap.svg
          git commit -m "Auto-Update Running Heatmap" || echo "No changes to commit"
          git push
